SITE-1118 Implement appropriate date/time format
Medable/ResearchKit pull request #30
Opened 2020-10-02 15:18 UTC by lukagabric

SITE-1118 Based on question type, depending if it is date time or date only, use and submit only the necessary calendar components with the task response.

2020-10-02 16:07 UTC, diederikh requested changes

2020-10-02 16:07 UTC, diederikh commented on ResearchKit/Common/ORKAnswerFormat.m
> +- (NSDate *)pickerDefaultDate
Can this not be done in `MDORKQuestionStepViewController.answerCellForTableView:`?

2020-10-02 16:20 UTC, lukagabric commented on ResearchKit/Common/ORKAnswerFormat.m
> +- (NSDate *)pickerDefaultDate
This is a private getter.

2020-10-05 10:41 UTC, diederikh commented on ResearchKit/Common/ORKAnswerFormat.m
> +- (NSDate *)pickerDefaultDate
You can expose the getter via a category. We do this all the time for other RK customizations.

2020-10-05 11:58 UTC, lukagabric commented on ResearchKit/Common/ORKAnswerFormat.m
> +- (NSDate *)pickerDefaultDate
I did not mean we cannot expose it, rather it is not worth it changing private implementation, it is easier to change in RK. See this conversation for reference: https://github.com/Medable/ResearchKit/pull/29

2020-10-09 06:03 UTC, lukagabric commented on ResearchKit/Common/ORKAnswerFormat.m
> +- (NSDate *)pickerDefaultDate
@diederikh I think our conversation from the watercooler resolve this?

2020-10-12 08:49 UTC, diederikh approved these changes

2020-10-13 15:28 UTC, merged